name: "PyVista Plotting"
on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test PyVista Plotting
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
      PYVISTA_OFF_SCREEN: 'True'
      ALLOW_PLOTTING: true
      SHELLOPTS: 'errexit:pipefail'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Headless Display
        run: |
          sudo apt-get update && sudo apt-get install libgl1-mesa-glx xvfb -y
          export DISPLAY=:99.0
          export PYVISTA_OFF_SCREEN=True
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run PyVista
        run: python -c "import pyvista;pyvista.Sphere().plot(screenshot='sphere.png')"
      - uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: sphere.png
